### ISSUE TITLE
Entity threw exception

### ISSUE THREAD

**Issue by PLESOP** [Bloom-host/Petal#1]
[22:39:08 ERROR]: Entity threw exception at world:481.5,137.6875,-5992.5
java.util.NoSuchElementException: No value present
        at java.util.Optional.get(Optional.java:143) ~[?:?]
        at net.minecraft.world.entity.ai.behavior.MoveToTargetSink.tick(MoveToTargetSink.java:105) ~[?:?]
        at net.minecraft.world.entity.ai.behavior.MoveToTargetSink.canStillUse(MoveToTargetSink.java:19) ~[?:?]
        at net.minecraft.world.entity.ai.behavior.Behavior.tickOrStop(Behavior.java:74) ~[petal-1.19.jar:git-Petal-"4c739e7"]
        at net.minecraft.world.entity.ai.Brain.tickEachRunningBehavior(Brain.java:430) ~[?:?]
        at net.minecraft.world.entity.ai.Brain.tick(Brain.java:375) ~[?:?]
        at net.minecraft.world.entity.npc.Villager.mobTick(Villager.java:357) ~[?:?]
        at net.minecraft.world.entity.npc.Villager.customServerAiStep(Villager.java:338) ~[?:?]
        at net.minecraft.world.entity.Mob.serverAiStep(Mob.java:910) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.aiStep(LivingEntity.java:3391) ~[?:?]
        at net.minecraft.world.entity.Mob.aiStep(Mob.java:665) ~[?:?]
        at net.minecraft.world.entity.AgeableMob.aiStep(AgeableMob.java:154) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:3033) ~[?:?]
        at net.minecraft.world.entity.Mob.tick(Mob.java:427) ~[?:?]
        at net.minecraft.world.entity.npc.Villager.tick(Villager.java:407) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1236) ~[?:?]
        at net.minecraft.server.level.ServerLevel.lambda$tick$6(ServerLevel.java:715) ~[?:?]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:42) ~[petal-1.19.jar:git-Petal-"4c739e7"]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:693) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1579) ~[petal-1.19.jar:git-Petal-"4c739e7"]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:485) ~[petal-1.19.jar:git-Petal-"4c739e7"]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1441) ~[petal-1.19.jar:git-Petal-"4c739e7"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1208) ~[petal-1.19.jar:git-Petal-"4c739e7"]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:307) ~[petal-1.19.jar:git-Petal-"4c739e7"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by BloomVPS** [comment]
Can you confirm that this still occurs on the latest release?

**Comment by PLESOP** [comment]
I mean, it's in an older version, but I doubt it's been fixed. This error first appeared to me an hour ago today.
If this has already been fixed, I'm not sure. That's why I'm sending it for checking.

**Comment by BloomVPS** [comment]
Please use the latest version, it is several builds ahead of the one you were given.

**Comment by PLESOP** [comment]
Yes, I'll try.

**Comment by KayaEdwin** [comment]
Any updates on this?

**Comment by BloomVPS** [comment]
Fixed in pre-release build
