### ISSUE TITLE
Entity prevented from being added/removed to world

### ISSUE THREAD

**Issue by kaxonomy** [Bloom-host/Petal#29]
I'm listening to the EntityAddToWorldEvent (this issue isn't exclusive to EntityAddToWorldEvent) as part of my chunk scanner to limit entities. However, I'm having trouble removing entities regardless if I'm using the main synchronous thread. I've also tried adding a `Bukkit#isPrimaryThread()` check before removing the entity, but I still receive the following error:
```
[15:31:34 WARN]: Entity EntityItem['Stone'/716, uuid='1491683a-1b2e-414c-83dc-787db3df535e', l='ServerLevel[world]', x=169.74, y=87.32, z=246.53, cpos=[10, 15], tl=0, v=true] is currently prevented from being added/removed to world since it is processing section status updates
java.lang.Throwable: null
	at net.minecraft.world.entity.Entity.setRemoved(Entity.java:4507) ~[petal-1.19.2.jar:git-petal-"cc69154"]
	at net.minecraft.world.entity.Entity.remove(Entity.java:706) ~[petal-1.19.2.jar:git-petal-"cc69154"]
	at net.minecraft.world.entity.Entity.discard(Entity.java:688) ~[petal-1.19.2.jar:git-petal-"cc69154"]
	at org.bukkit.craftbukkit.v1_19_R1.entity.CraftEntity.remove(CraftEntity.java:693) ~[petal-1.19.2.jar:git-petal-"cc69154"]
	at tech.kaxon.vlsurvival.listeners.SpawnListener.remove(SpawnListener.java:228) ~[VLSurvival.jar:?]
	at tech.kaxon.vlsurvival.listeners.SpawnListener.removeEntity(SpawnListener.java:219) ~[VLSurvival.jar:?]
	at tech.kaxon.vlsurvival.listeners.SpawnListener.onSpawn(SpawnListener.java:177) ~[VLSurvival.jar:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[petal-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[petal-api-1.19.2-R0.1-SNAPSHOT.jar:git-petal-"cc69154"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[petal-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:678) ~[petal-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.event.Event.callEvent(Event.java:45) ~[petal-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.level.ServerLevel$EntityCallbacks.onTrackingStart(ServerLevel.java:2674) ~[?:?]
	at net.minecraft.server.level.ServerLevel$EntityCallbacks.c(ServerLevel.java:2603) ~[?:?]
	at io.papermc.paper.chunk.system.entity.EntityLookup.entityStatusChange(EntityLookup.java:265) ~[petal-1.19.2.jar:git-petal-"cc69154"]
	at io.papermc.paper.chunk.system.entity.EntityLookup.addEntity(EntityLookup.java:388) ~[petal-1.19.2.jar:git-petal-"cc69154"]
	at io.papermc.paper.chunk.system.entity.EntityLookup.addNewEntity(EntityLookup.java:326) ~[petal-1.19.2.jar:git-petal-"cc69154"]
	at net.minecraft.server.level.ServerLevel.addEntity(ServerLevel.java:1565) ~[?:?]
	at net.minecraft.server.level.ServerLevel.addFreshEntity(ServerLevel.java:1468) ~[?:?]
	at net.minecraft.server.level.ServerLevel.addFreshEntity(ServerLevel.java:1463) ~[?:?]
	at net.minecraft.server.level.ServerPlayer.drop(ServerPlayer.java:2378) ~[?:?]
	at net.minecraft.world.entity.player.Player.drop(Player.java:752) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleSetCreativeModeSlot(ServerGamePacketListenerImpl.java:3609) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundSetCreativeModeSlotPacket.handle(ServerboundSetCreativeModeSlotPacket.java:18) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundSetCreativeModeSlotPacket.handle(ServerboundSetCreativeModeSlotPacket.java:12) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[petal-1.19.2.jar:git-petal-"cc69154"]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1368) ~[petal-1.19.2.jar:git-petal-"cc69154"]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[petal-1.19.2.jar:git-petal-"cc69154"]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1345) ~[petal-1.19.2.jar:git-petal-"cc69154"]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1338) ~[petal-1.19.2.jar:git-petal-"cc69154"]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1316) ~[petal-1.19.2.jar:git-petal-"cc69154"]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1204) ~[petal-1.19.2.jar:git-petal-"cc69154"]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:310) ~[petal-1.19.2.jar:git-petal-"cc69154"]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by kaxonomy** [comment]
Moved to purpur issue [#1212](https://github.com/PurpurMC/Purpur/issues/1212)
