### ISSUE TITLE
FastAsyncWorldEdit throwing errors during startup & using `//mask`

### ISSUE THREAD

**Issue by Log1x** [Bloom-host/Petal#6]
Using the latest version of FastAsyncWorldEdit and Petal, `//mask` appears to be broken. 

The log is long so I didn't want to post it in the issue: https://bin.bloom.host/garegeraju.log 

**Steps to reproduce**
1) Get a stick
2) `//br sphere grass_block`
3) `//mask stone`
4) Right click

It is also throwing an exception during startup:

```log
[03:44:40 WARN]: java.lang.NoSuchFieldException: t
[03:44:40 WARN]:        at java.base/java.lang.Class.getDeclaredField(Class.java:2610)
[03:44:40 WARN]:        at FastAsyncWorldEdit.jar//com.sk89q.worldedit.bukkit.adapter.impl.fawe.v1_19_R1.PaperweightPlatformAdapter.<clinit>(PaperweightPlatformAdapter.java:151)
[03:44:40 WARN]:        at java.base/java.lang.Class.forName0(Native Method)
[03:44:40 WARN]:        at java.base/java.lang.Class.forName(Class.java:375)
[03:44:40 WARN]:        at FastAsyncWorldEdit.jar//com.sk89q.worldedit.bukkit.adapter.BukkitImplLoader.loadAdapter(BukkitImplLoader.java:170)
[03:44:40 WARN]:        at FastAsyncWorldEdit.jar//com.sk89q.worldedit.bukkit.WorldEditPlugin.loadAdapter(WorldEditPlugin.java:361)
[03:44:40 WARN]:        at FastAsyncWorldEdit.jar//com.sk89q.worldedit.bukkit.WorldEditPlugin.setupPreWorldData(WorldEditPlugin.java:232)
[03:44:40 WARN]:        at FastAsyncWorldEdit.jar//com.sk89q.worldedit.bukkit.WorldEditPlugin.onEnable(WorldEditPlugin.java:205)
[03:44:40 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[03:44:40 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[03:44:40 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:547)
[03:44:40 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:594)
[03:44:40 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:508)
[03:44:40 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:314)
[03:44:40 WARN]:        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1137)
[03:44:40 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:307)
[03:44:40 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

These issues do not occur on Paper.

**Comment by KayaEdwin** [comment]
Could you check if the issue occurs on Purpur? You can download their latest build at https://purpurmc.org

**Comment by Log1x** [comment]
This issue was discussed in Discord. It actually isn't present in pre 2 – it was from a pre-release jar posted in #petal-community-support.

& no it doesn't occur on Purpur.

**Comment by AVuTuVA** [comment]
https://ci.athion.net/job/FastAsyncWorldEdit/lastSuccessfulBuild/artifact/artifacts/FastAsyncWorldEdit-Bukkit-2.4.2-SNAPSHOT-249.jar
