### ISSUE TITLE
Error on latest build 

### ISSUE THREAD

**Issue by KayaEdwin** [Bloom-host/Petal#7]
[20:33:08 ERROR]: Entity threw exception at Overworld:-1256.431526762105,26.0,11172.153295030048
java.util.NoSuchElementException: No value present
        at java.util.Optional.get(Optional.java:143) ~[?:?]
        at net.minecraft.world.entity.ai.behavior.MoveToTargetSink.tick(MoveToTargetSink.java:114) ~[?:?]
        at net.minecraft.world.entity.ai.behavior.MoveToTargetSink.canStillUse(MoveToTargetSink.java:21) ~[?:?]
        at net.minecraft.world.entity.ai.behavior.Behavior.tickOrStop(Behavior.java:74) ~[petal-1.19.jar:git-petal-"7b3fb09"]
        at net.minecraft.world.entity.ai.Brain.tickEachRunningBehavior(Brain.java:430) ~[?:?]
        at net.minecraft.world.entity.ai.Brain.tick(Brain.java:375) ~[?:?]
        at net.minecraft.world.entity.npc.Villager.mobTick(Villager.java:357) ~[?:?]
        at net.minecraft.world.entity.npc.Villager.customServerAiStep(Villager.java:338) ~[?:?]
        at net.minecraft.world.entity.Mob.serverAiStep(Mob.java:910) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.aiStep(LivingEntity.java:3393) ~[?:?]
        at net.minecraft.world.entity.Mob.aiStep(Mob.java:665) ~[?:?]
        at net.minecraft.world.entity.AgeableMob.aiStep(AgeableMob.java:154) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:3035) ~[?:?]
        at net.minecraft.world.entity.Mob.tick(Mob.java:427) ~[?:?]
        at net.minecraft.world.entity.npc.Villager.tick(Villager.java:407) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1236) ~[?:?]
        at net.minecraft.server.level.ServerLevel.lambda$tick$6(ServerLevel.java:715) ~[?:?]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:42) ~[petal-1.19.jar:git-petal-"7b3fb09"]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:693) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1579) ~[petal-1.19.jar:git-petal-"7b3fb09"]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:485) ~[petal-1.19.jar:git-petal-"7b3fb09"]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1441) ~[petal-1.19.jar:git-petal-"7b3fb09"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1208) ~[petal-1.19.jar:git-petal-"7b3fb09"]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:307) ~[petal-1.19.jar:git-petal-"7b3fb09"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by Wesley51** [comment]
Any steps to reproduce?

**Comment by KayaEdwin** [comment]
Haven't found any steps to reproduce, just reporting the error

**Comment by peaches94** [comment]
https://github.com/Bloom-host/Petal/releases/tag/1.19-pre-3
